# Using the official Node.js image as a base
FROM node:14

# Set working directory in container
WORKDIR /app

# Copy client files from the build context to container
COPY . .

# Debug: List contents of /app
RUN ls -la /app

# Install dependencies
RUN npm install

# Build the React app
RUN npm build

# Command to run React app
CMD ["npm", "start"]
