# Intermediate stage for building the server
FROM node:16 AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the 'package.json' and 'package-lock.json' to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build your server app (if necessary)
RUN npm build

# Final stage for the server container
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy the 'node_modules' directory from the builder stage
COPY --from=builder /app/node_modules ./node_modules

# Copy the rest of the application code from the builder stage
COPY --from=builder /app .

# Expose the port the server will listen on
EXPOSE 4000

# Command to start the server
CMD ["node", "src/App.js"]
