# Using the official Node.js image as a base
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy files from server to container
COPY . .

# Install dependencies
RUN npm install

# Expose the port the server will listen on
EXPOSE 3000

# Command to start the server
CMD ["node", "app.js"]